components:
  schemas:
    Hello:
      description: "Simple response"
      properties:
        familyName:
          description: The author's surname.
          readOnly: true
          type: string
      type: object
openapi: 3.0.1
info:
  description: "simple hello"
  license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "hello"
  version: v1.0
paths:
  "/hello/{name}":
    get:
      operationId: getHello
      tags: ["Hello"]
      description: simple hello
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hello"
            application/xml:
              schema:
                $ref: "#/components/schemas/Hello"


