components:
  schemas:
    Response:
      description: "Simple response"
      properties:
        greeting:
          description: "Full greeting"
          type: string
      type: object
info:
  description: ""
  title: Hello
  version: v1.0
openapi: "3.0.1"
paths:
  /:
    get:
      description: "simple hello"
      operationId: hello
      parameters:
        -
          in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: ""
      summary: "Just hello"
      tags:
        - Hello
