components:
  schemas:
    Response:
      description: "Simple response"
      properties:
        greeting:
          description: "Full greeting"
          type: string
      type: object
info:
  description: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: Hello
  version: v1.0
openapi: 3.0.1
paths:
  "/hello/{name}":
    get:
      operationId: getGreet
      tags: ["HelloWorld"]
      description: "simple hello"
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
          description: ""

